language: go

dist: xenial

go:
  - 1.13.x
  - 1.14.x

env:
  - GO111MODULE=on

before_install:
  - go get golang.org/x/tools/cmd/goimports
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - diff -u <(echo -n) <(goimports -d .)
  - golangci-lint run -v --disable-all
    --enable=govet
    --enable=staticcheck
    --enable=ineffassign
    --enable=misspell
    ./...
  - go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
