apiVersion: datasource.sentinel.io/v1
kind: SystemRules
metadata:
  name: systemrules-sample
spec:
  # Add fields here
  rules:
    - metricType: AvgRT
      strategy: NoAdaptive
      triggerCount: 123
    - metricType: Concurrency
      strategy: NoAdaptive
      triggerCount: 100